name: .NET Core

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
#     - uses: actions/checkout@master
#     - run: dotnet build --configuration Release AbpHelper/AbpHelper.csproj
#     - name: Create the package
#       run: dotnet pack --configuration Release AbpHelper/AbpHelper.csproj
#     - name: Publish the package to GPR
#       run: dotnet nuget push .\AbpHelper\bin\Release\DosSEdo.AbpHelper.0.5.1.nupkg -k oy2mqaw37ifhslr5kpiqng4s2ww5bute3koomvslnkcvtu -s https://api.nuget.org/v3/index.json
