name: publish to nuget
on:
  push:
    branches:
      - master
      - develop
jobs:
  publish:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/AbpHelper/AbpHelper.csproj
        VERSION_FILE_PATH: src/AbpHelper/AbpHelper.csproj
        PACKAGE_NAME: Dosse.AbpHelper.CLI
        NUGET_KEY: ${{ secrets.NUGET_KEY_M }}
        NUGET_SOURCE: https://api.nuget.org/v3/index.json
