name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
      - develop
jobs:
  publish:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/AbpHelper/AbpHelper.csproj
        VERSION_FILE_PATH: src/AbpHelper/AbpHelper.csproj
        PACKAGE_NAME: AbpHelper.CLI
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        NUGET_SOURCE: https://nuget.pkg.github.com/DosSEdo/
